### ISSUE TITLE
Error in enable-button.rb when body is instance of Rack::BodyProxy (Spree Commerce)

### ISSUE THREAD

**Issue by puckbag** [pboling/rack-insight#38]
Adding Rack::Insight makes a fresh install of Spree error.

As @phoenixek12 mentioned on 71226db7fa56cd26a534b0206127442032b8b01e, Rack::BodyProxy does not implement empty?.

```
undefined method `empty?' for #<ActionDispatch::Response:0x007fd073d6a8a8>
rack (1.5.2) lib/rack/body_proxy.rb:36:in `method_missing'
rack-insight (0.5.30) lib/rack/insight/enable-button.rb:21:in `call'
rack-insight (0.5.30) lib/rack/insight/app.rb:62:in `call'
```

**Comment by pboling** [comment]
version of rails, rack?

**Comment by puckbag** [comment]
Using rack 1.5.2
Using rails 4.1.8

I just created pull request #39

**Comment by pboling** [comment]
I have rewritten the entire enable button class.  This is now fixed for all Rack frameworks.
